### ISSUE TITLE
0.5.0 Plugin crashes on firs usage

### ISSUE THREAD

**Issue by scottleedavis** [mattermost/mattermost-plugin-autolink#49]
After trying to update the plugin on a 5.10 server it crashes on first time it tries to autolink.

**Comment by ThiefMaster** [comment]
Happens for me as well, except that it works fine localyl and on my staging server but in production is also dies quickly:
```
2019-04-18T09:54:42.251Z error mlog/log.go:172 RPC call MessageWillBePosted to plugin failed. {"plugin_id": "mattermost-autolink", "error": "unexpected EOF"}
2019-04-18T09:54:44.070Z error mlog/log.go:172 RPC call MessageWillBePosted to plugin failed. {"plugin_id": "mattermost-autolink", "error": "connection is shut down"}
```

**Comment by ThiefMaster** [comment]
Debug log:

```
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	panic: runtime error: invalid memory address or nil pointer dereference	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9d578c]	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	goroutine 56 [running]:	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/model.(*AppError).Error(...)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/model/utils.go:57	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	main.(*Plugin).MessageWillBePosted.func1(0xa7c740, 0xc0002a7260, 0xc4b520)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/plugin.go:92 +0x63c	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.Inspect.func1.1(0xc4b520, 0xc0002a7260, 0xc0002a7260)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:18 +0x42	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.InspectInline(0xc4b520, 0xc0002a7260, 0xc0002d59c8)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:56 +0x3e	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.Inspect.func1(0xc5cb40, 0xc000296e40, 0xc0002a7240)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:17 +0x19f	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.998Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0xc5cb40, 0xc000296e40, 0xc0002d5ac8)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.999Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:29 +0x3e	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.999Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0xc5ca00, 0xc0002a7220, 0xc0002d5ac8)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.999Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:35 +0x16c	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:32.999Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown.Inspect(0xc0002d04e0, 0x27, 0xc000234b40)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.000Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:10 +0xa7	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.001Z	debug	plugin/hclog_adapter.go:34	main.(*Plugin).MessageWillBePosted(0xc00020e150, 0xc00029ea60, 0xc0003ba000, 0x7fd642e930d8, 0xc00020e150, 0x1)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/plugin.go:49 +0x11e	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34	github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).MessageWillBePosted(0xc00000e620, 0xc00029ea50, 0xc0002a7200, 0x0, 0x0)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34		/home/jespino/.gocode/src/github.com/mattermost/mattermost-plugin-autolink/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc_generated.go:151 +0x7c	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34	reflect.Value.call(0xc00029c660, 0xc0002aa0e0, 0x13, 0xb518ce, 0x4, 0xc000234f18, 0x3, 0x3, 0xc0002963c0, 0x0, ...)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34		/usr/lib/go/src/reflect/value.go:447 +0x461	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34	reflect.Value.Call(0xc00029c660, 0xc0002aa0e0, 0x13, 0xc000224f18, 0x3, 0x3, 0x0, 0x0, 0x0)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34		/usr/lib/go/src/reflect/value.go:308 +0xa4	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.002Z	debug	plugin/hclog_adapter.go:34	net/rpc.(*service).call(0xc0002960c0, 0xc0002a8140, 0xc0002ae188, 0xc0002ae1b0, 0xc0002be300, 0xc0002a6920, 0xa25800, 0xc00029ea50, 0x16, 0xa25840, ...)	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.003Z	debug	plugin/hclog_adapter.go:34		/usr/lib/go/src/net/rpc/server.go:384 +0x14e	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.003Z	debug	plugin/hclog_adapter.go:34	created by net/rpc.(*Server).ServeCodec	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.003Z	debug	plugin/hclog_adapter.go:34		/usr/lib/go/src/net/rpc/server.go:481 +0x42b	{"plugin_id": "mattermost-autolink"}
2019-04-18T10:10:33.003Z	error	mlog/log.go:172	RPC call MessageWillBePosted to plugin failed.	{"plugin_id": "mattermost-autolink", "error": "unexpected EOF"}
2019-04-18T10:10:33.003Z	debug	plugin/hclog_adapter.go:32	plugin process exited	{"plugin_id": "mattermost-autolink", "wrapped_extras": "pathplugins/mattermost-autolink/server/dist/plugin-linux-amd64pid269errorexit status 2"}
```

**Comment by ThiefMaster** [comment]
OK, any DM crashes the plugin, probably doing stuff with a nil team somewhere..
